id: PAA4BC8B9
initial_creation_type: input
source_metadata:
  title: Nyāyasūtra with Vātsyāyana's Nyāyabhāṣya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Nyāya
  data entry: Indology Student Team, University of Tokyo
  contribution to GRETIL: Indology Student Team, University of Tokyo
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:03:03.536163'
last_modified_at: '2022-03-09T15:03:03.536176'
